---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: docker
lint: |
  set -e
  ansible-lint
platforms:
  - name: ${MOLECULE_DISTRO:-debian12}
    image: "geerlingguy/docker-${MOLECULE_DISTRO}-ansible:latest"
    pre_build_image: true
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run:rw,exec,mode=1777,size=65536k
      - /tmp/.ansible:rw,exec,mode=1777,size=65536k
      - /tmp/ansible-tmp:rw,exec,mode=1777,size=65536k
      - /var/tmp:rw,exec,mode=1777,size=65536k
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_ROLES_PATH: ../../..
    ANSIBLE_BECOME: "true"
    ANSIBLE_BECOME_METHOD: "sudo"
    ANSIBLE_BECOME_USER: "root"
  config_options:
    defaults:
      remote_tmp: /tmp
      local_tmp: /tmp
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: auto_silent
        ansible_become: true
        ansible_become_method: sudo
verifier:
  name: ansible
