---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'
      become: true

    - name: Update dnf cache (RedHat)
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts['os_family'] == 'RedHat'
      become: true
